import { useEffect, useState } from "react";
import "tailwindcss/tailwind.css";
import "../styles/App.css";

function MyApp({ Component, pageProps }) {
  const [data, setData] = useState([
    { name: "blog-series-collapsible", code: "" },
    { name: "blog-similar-article-cover", code: "" },
    { name: "blog-more-articles-wrapper", code: "" },
    { name: "blog-post-detail-card", code: "" },
    { name: "blog-content-wrapper", code: "" },
    { name: "blog-content-main", code: "" },
    { name: "blog-subscription-article-wrapper", code: "" },
    { name: "blog-content-sidebar", code: "" },
    { name: "blog-more-articles", code: "" },
    { name: "blog-more-articles-title", code: "" },
    { name: "blog-more-articles-wrapper", code: "" },
    { name: "blog-comments-section-wrapper", code: "" },
    { name: "blog-series", code: "" },
    { name: "blog-series-heading", code: "" },
    { name: "blog-series-list", code: "" },
    { name: "blog-author-card", code: "" },
    { name: "blog-author-area-photo", code: "" },
    { name: "blog-author-area-name", code: "" },
    { name: "blog-follow-wrapper", code: "" },
    { name: "blog-followers-count", code: "" },
    { name: "blog-main-logo", code: "" },
    { name: "blog-logo", code: "" },
    { name: "blog-title", code: "" },
    { name: "blog-search-button", code: "" },
    { name: "blog-theme-switcher", code: "" },
    { name: "blog-settings", code: "" },
    { name: "blog-menu-container", code: "" },
    { name: "blog-menu-profile", code: "" },
    { name: "blog-menu", code: "" },
    { name: "blog-menu-item", code: "" },
    { name: "blog-more-icon", code: "" },
    { name: "blog-sub-header", code: "" },
    { name: "blog-sub-header-nav", code: "" },
    { name: "blog-nav-active", code: "" },
    { name: "blog-social-media-section", code: "" },
    { name: "blog-post-card", code: "" },
    { name: "blog-post-card-wrapper", code: "" },
    { name: "blog-post-card-title", code: "" },
    { name: "blog-post-card-meta", code: "" },
    { name: "blog-post-card-author-pic", code: "" },
    { name: "blog-post-card-author-name", code: "" },
    { name: "blog-post-card-time", code: "" },
    { name: "blog-post-card-brief", code: "" },
    { name: "blog-post-card-cover", code: "" },
    { name: "blog-posts-wrapper", code: "" },
    { name: "blog-posts-end-card", code: "" },
    { name: "blog-body", code: "" },
    { name: "blog-author-area", code: "" },
    { name: "blog-content-area", code: "" },
    { name: "blog-subscription-form", code: "" },
    { name: "blog-post-area", code: "" },
    { name: "blog-page-area", code: "" },
    { name: "blog-series-card", code: "" },
    { name: "blog-series-label", code: "" },
    { name: "blog-series-title", code: "" },
    { name: "blog-series-desc", code: "" },
    { name: "blog-series-cover-container", code: "" },
    { name: "blog-series-cover", code: "" },
    { name: "blog-title", code: "" },
    { name: "blog-header", code: "" },
    { name: "blog-follow-button", code: "" },
    { name: "blog-footer-area", code: "" },
    { name: "blog-impressum", code: "" },
    { name: "blog-footer-credits", code: "" },
    { name: "blog-page-card", code: "" },
    { name: "blog-page-content", code: "" },
    { name: "blog-page-title", code: "" },
    { name: "blog-series-item", code: "" },
    { name: "blog-series-cover", code: "" },
    { name: "blog-series-cover-container", code: "" },
    { name: "blog-series-content", code: "" },
    { name: "blog-series-number", code: "" },
    { name: "blog-similar-article", code: "" },
    { name: "blog-similar-article-wrapper", code: "" },
    { name: "blog-similar-author-wrapper", code: "" },
    { name: "blog-similar-author-photo", code: "" },
    { name: "blog-similar-author-name", code: "" },
    { name: "blog-post-details", code: "" },
    { name: "blog-subscription-form-wrapper", code: "" },
    { name: "blog-subscription-form-message", code: "" },
    { name: "blog-subscription-form-input", code: "" },
    { name: "blog-subscription-form-button", code: "" },
    { name: "blog-subscription-form-check-icon", code: "" },
    { name: "blog-subscription-form-subscribed-title", code: "" },
    { name: "blog-subscription-form-subscribed-message", code: "" },
    { name: "blog-page-title", code: "" },
  ]);
  const [basicStyles, setBasicStyles] = useState(
    `@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300&display=swap')\n\n* {\n  box-sizing: border-box;\n}\n\nbody {\n  height: 100%;\n  font-family: "Inter", sans-serif;\n}`
  );
  const [chosenElement, setChosenElement] = useState("");

  const props = {
    data,
    setData,
    chosenElement,
    setChosenElement,
    basicStyles,
    setBasicStyles,
  };

  return <Component {...pageProps} {...props} />;
}

export default MyApp;
